name: repo-index-postgres
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: cocoindex
      POSTGRES_USER: cocoindex
      POSTGRES_DB: cocoindex
    ports:
      - 5432:5432

volumes:
  postgres_data: